[package]
name = "pouch-sdk"
description = "The SDK to interact with pouch-server"
version.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
