name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Code Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
  bazel:
    name: Bazel
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazelisk test //...

      - name: Coverage
        run: bazelisk coverage //...

      - name: Build
        run: bazelisk build //...