name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Code Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
  debug-linux:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    name: Build ${{ matrix.target }} debug binary
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust target
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
          rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target=${{ matrix.target }}
  debug-macos:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    name: Build ${{ matrix.target }} debug binary
    runs-on: macos-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust target
        run: |
          rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target=${{ matrix.target }}
  debug-windows:
    strategy:
      matrix:
        target:
          - aarch64-pc-windows-msvc
          - x86_64-pc-windows-msvc
    name: Build ${{ matrix.target }} debug binary
    runs-on: windows-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust target
        run: |
          rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --target=${{ matrix.target }}